<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inchoo PHP Academy 2019</title>
    <script src="<?php echo App::config('url');?>assets/jquery-3.3.1.slim.min.js"></script>
    <link rel="stylesheet" href="<?php echo App::config('url');?>assets/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="<?php echo App::config('url');?>assets/style.css">
    <script src="<?php echo App::config('url');?>assets/bootstrap/js/bootstrap.js"></script>
</head>
<body>

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<?php echo App::config('url') ?>">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main role="main" class="flex-shrink-0 top-space">
    <div class="container">
        <?php echo $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3">
    <div class="container">
        <span class="text-muted">PHPInchooAkademija Zadaća 6</span>
    </div>
</footer>


</body>
</html>