<p><?= htmlspecialchars($post->getContent()) ?></p>

<?php $post_id = (int)$post->getId(); ?>

<a href="<?php echo App::config('url').'Index/delete/'.$post->getID();?>">DELETE POST</a>
<h3>Comments</h3>

<form method="post" action="<?php echo App::config('url') ?>Index/newComment">

    <div class="form-group">
        <label for="content">Add a comment</label>
        <input id="content" name="content"><br>
        <input type="hidden" name="post_id" id="post_id" value="<?php echo $post_id; ?>" />

    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>

<?php
foreach ($comment as $comment){

    if ($comment->post_id == $post_id) {
        echo $comment->content;
        echo '<br>';
    }


}
?>

