<p><?= htmlspecialchars($post->getContent()) ?></p>

<?php $post_id = (int)$post->getId();

?>
<h3>Comments</h3>

<form method="post" action="<?php echo App::config('url') ?>Index/newComment">

    <div class="form-group">
        <label for="comment">Add a comment</label>
        <input id="comment" name="comment"><br>
        <input type="hidden" name="post_id" id="post_id" value="<?php echo $post_id; ?>" />

    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>

<?php

?>

